// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iamiurlszfdpmfgmshhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhbWl1cmxzemZkcG1mZ21zaGhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3MjU4MjUsImV4cCI6MjA3NjMwMTgyNX0.l-Wmspjx1CTqytWJGu4KWsQ8if9uPstjqLhFx2qNUpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});